global using BarcodeScanning;
global using System.ComponentModel;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Runtime.CompilerServices;
global using System.Windows.Input;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Maui.Views;
global using Duende.IdentityModel.OidcClient;
global using Duende.IdentityModel.OidcClient.Browser;
global using Microsoft.Extensions.Logging;
global using Refit;
global using TinyStorage.Clients;
global using TinyStorage.Clients.Models.Requests;
global using TinyStorage.Clients.Models.Responses;
global using TinyStorage.Services;
global using TinyStorage.Services.Abstractions;
global using TinyStorage.Services.Handlers;
global using TinyStorage.ViewModels;
global using TinyStorage.ViewModels.Abstractions;
global using TinyStorage.Views;
global using TinyStorage.Views.Popups;
global using IBrowser = Duende.IdentityModel.OidcClient.Browser.IBrowser;

